# Generated by Django 5.0.4 on 2024-04-11 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_text', models.CharField(max_length=15)),
                ('english_text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('content', models.TextField(blank=True, null=True)),
                ('imageUrl', models.JSONField(blank=True, default=dict, null=True, verbose_name='imageUrl')),
                ('date', models.DateField()),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_website.classification')),
            ],
        ),
    ]
