# Generated by Django 5.0.4 on 2024-04-11 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='english_text',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_website.classification', to_field='english_text'),
        ),
    ]
