# Generated by Django 5.0.4 on 2024-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0006_position_remove_member_position_member_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='member',
        ),
        migrations.AddField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(null=True, to='cash_website.member'),
        ),
    ]
