# Generated by Django 5.0.4 on 2024-04-13 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0007_remove_project_member_project_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='cash_website.member'),
        ),
    ]
