# Generated by Django 5.0.4 on 2024-04-17 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0010_snippet_highlighted_snippet_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='education',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='experience',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='office',
            field=models.CharField(max_length=10),
        ),
    ]
