# Generated by Django 5.0.4 on 2024-04-18 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0012_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads')),
                ('related_new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cash_website.new')),
            ],
        ),
    ]
