# Generated by Django 5.0.4 on 2024-04-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0013_newimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newimage',
            name='related_new',
        ),
    ]
