# Generated by Django 5.0.4 on 2024-04-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0014_remove_newimage_related_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newimage',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
    ]
