# Generated by Django 5.0.4 on 2024-04-21 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0015_alter_newimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousels')),
            ],
        ),
        migrations.AddField(
            model_name='newimage',
            name='related_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cash_website.new'),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('related_project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cash_website.project')),
            ],
        ),
    ]
