# Generated by Django 5.0.4 on 2024-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0016_carouselimage_newimage_related_new_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='displayornot',
            field=models.BooleanField(default=True),
        ),
    ]
