# Generated by Django 5.0.4 on 2024-04-24 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0017_carouselimage_displayornot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classification',
            name='chinese_text',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='new',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_website.classification', to_field='chinese_text'),
        ),
        migrations.AlterField(
            model_name='project',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cash_website.projectclassification', to_field='chinese_text'),
        ),
        migrations.AlterField(
            model_name='projectclassification',
            name='chinese_text',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
