# Generated by Django 5.0.4 on 2024-04-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0018_alter_classification_chinese_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='imageUrl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
