# Generated by Django 5.0.4 on 2024-04-25 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0020_alter_carouselimage_displayornot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='displayornot',
            field=models.BooleanField(default=True),
        ),
    ]
