# Generated by Django 5.0.4 on 2024-04-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0021_alter_carouselimage_displayornot'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='order',
            field=models.IntegerField(default=999),
        ),
    ]
