# Generated by Django 5.0.4 on 2024-04-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0023_rename_member_employee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselimage',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
