# Generated by Django 5.0.4 on 2024-04-30 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0024_alter_carouselimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.AddField(
            model_name='project',
            name='endDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='startDate',
            field=models.DateField(null=True),
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
