# Generated by Django 5.0.4 on 2024-04-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0025_remove_snippet_owner_delete_test_remove_project_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='experience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='office',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ManyToManyField(blank=True, null=True, to='cash_website.position'),
        ),
    ]
