# Generated by Django 5.0.4 on 2024-05-03 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0027_alter_employee_name_alter_employee_position_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='carouselimage',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='可讀', max_length=15),
        ),
    ]
