# Generated by Django 5.0.4 on 2024-05-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0030_award'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='subtitle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
