# Generated by Django 5.0.4 on 2024-05-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0032_membercount_remove_project_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=10, null=True)),
                ('externalId', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Award',
        ),
    ]
