# Generated by Django 5.0.4 on 2024-05-15 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0033_historyaward_delete_award'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyaward',
            name='category',
        ),
        migrations.RemoveField(
            model_name='historyaward',
            name='externalId',
        ),
        migrations.AddField(
            model_name='historyaward',
            name='link',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
