# Generated by Django 5.0.4 on 2024-05-17 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0034_remove_historyaward_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChosenAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
                ('imageUrl', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChosenAwardImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='chosenAward')),
                ('related_chosenAward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image', to='cash_website.chosenaward')),
            ],
        ),
    ]
