# Generated by Django 5.0.4 on 2024-05-18 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash_website', '0035_chosenaward_chosenawardimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chosenaward',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='chosenaward',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chosenAward'),
        ),
        migrations.DeleteModel(
            name='ChosenAwardImage',
        ),
    ]
